In [28]:
!pip install sqlalchemy
!pip install psycopg2
!pip install pandas
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.15.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (2.9.11)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\LENOVO-PC\AppData\Roaming\Python\Python313\site-packages (2.3.3)

# Imports Necesarios

In [29]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

# Engine para conexión con la BD

In [30]:
engine = create_engine("postgresql://neondb_owner:npg_zeS5q0GJZvds@ep-purple-poetry-aidpr2sf-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require")

# Carga del Dataset

In [31]:
df = pd.read_csv('customer_shopping_data.csv')
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

# Tablas para BD

In [32]:
TABLE_INVOICES_SALES = 'invoice_sales'
TABLE_DIM_CUSTOMERS = 'dim_customers'
TABLE_DIM_PRODUCTS = 'dim_products'
TABLE_DIM_TIME = 'dim_time'
TABLE_PAYMENTS = 'dim_payment_methods'
TABLE_SHOPPING_MALL = 'dim_shopping_malls'

# Dim Products

In [33]:

dim_products = df[["category"]].copy()
dim_products["id_dim_product"] = dim_products.index + 1
dim_products = dim_products[["id_dim_product", "category"]]
dim_products.head()

   id_dim_product  category
0               1  Clothing
1               2     Shoes
2               3  Clothing
3               4     Shoes
4               5     Books

In [34]:
dim_products.to_sql(TABLE_DIM_PRODUCTS, engine, if_exists='append', index=False)

457

# Dim Customers

In [35]:
dim_customers = df[["customer_id", "gender", "age"]].copy()
dim_customers = dim_customers.rename(columns={"customer_id": "id_customer"})
dim_customers.head()

  id_customer  gender  age
0     C241288  Female   28
1     C111565    Male   21
2     C266599    Male   20
3     C988172  Female   66
4     C189076  Female   53

In [36]:
dim_customers.to_sql(TABLE_DIM_CUSTOMERS, engine, if_exists='append', index=False)

457

# Dim Time

In [37]:
dim_time = df[["invoice_date"]].copy()

# Convertir a datetime y extraer componentes
dim_time["invoice_date"] = pd.to_datetime(dim_time["invoice_date"], dayfirst=True)
dim_time["id_dim_time"] = dim_time.index + 1

dim_time["day"] = dim_time["invoice_date"].dt.day
dim_time["month"] = dim_time["invoice_date"].dt.month
dim_time["year"] = dim_time["invoice_date"].dt.year

dim_time = dim_time[["id_dim_time", "invoice_date", "day", "month", "year"]]
dim_time.head()

   id_dim_time invoice_date  day  month  year
0            1   2022-08-05    5      8  2022
1            2   2021-12-12   12     12  2021
2            3   2021-11-09    9     11  2021
3            4   2021-05-16   16      5  2021
4            5   2021-10-24   24     10  2021

In [38]:

dim_time.to_sql(TABLE_DIM_TIME, engine, if_exists='append', index=False)

457

# Dim Shopping Malls

In [39]:
dim_shopping_malls = df[["shopping_mall"]].copy()
dim_shopping_malls = dim_shopping_malls.rename(columns={"shopping_mall": "shopping_mall_name"})
dim_shopping_malls["id_dim_shopping_mall"] = dim_shopping_malls.index + 1
dim_shopping_malls = dim_shopping_malls[["id_dim_shopping_mall", "shopping_mall_name"]]
dim_shopping_malls.head()

   id_dim_shopping_mall shopping_mall_name
0                     1             Kanyon
1                     2     Forum Istanbul
2                     3          Metrocity
3                     4       Metropol AVM
4                     5             Kanyon

In [40]:
dim_shopping_malls.to_sql(TABLE_SHOPPING_MALL, engine, if_exists='append', index=False)

457

# Dim Payments Methods

In [41]:
dim_payment_methods = df[["payment_method"]].copy()
dim_payment_methods = dim_payment_methods.rename(columns={"payment_method": "payment_method_name"})
dim_payment_methods["id_dim_payment_method"] = dim_payment_methods.index + 1
dim_payment_methods = dim_payment_methods[["id_dim_payment_method", "payment_method_name"]]
dim_payment_methods.head()

   id_dim_payment_method payment_method_name
0                      1         Credit Card
1                      2          Debit Card
2                      3                Cash
3                      4         Credit Card
4                      5                Cash

In [42]:
dim_payment_methods.to_sql(TABLE_PAYMENTS, engine, if_exists='append', index=False)

457

# Invoice Sales

In [43]:
invoice_sales = df[["invoice_no", "price", "quantity"]].copy()
invoice_sales = invoice_sales.rename(columns={"invoice_no": "id_invoice"})
invoice_sales["id_customer"] = dim_customers["id_customer"].copy()
invoice_sales["id_dim_product"] = dim_products["id_dim_product"].copy()
invoice_sales["id_dim_payment_method"] = dim_payment_methods["id_dim_payment_method"].copy()
invoice_sales["id_dim_shopping_mall"] = dim_shopping_malls["id_dim_shopping_mall"].copy()
invoice_sales["id_dim_time"] = dim_time["id_dim_time"].copy()

invoice_sales = invoice_sales[["id_invoice", "id_customer", "id_dim_product", "id_dim_payment_method", "id_dim_shopping_mall", "id_dim_time", "quantity", "price"]]
invoice_sales.head()

,id_invoice,id_customer,id_dim_product,id_dim_payment_method,id_dim_shopping_mall,id_dim_time,quantity,price
0,I138884,C241288,1,1,1,1,5,1500.40
1,I317333,C111565,2,2,2,2,3,1800.51
2,I127801,C266599,3,3,3,3,1,300.08
3,I173702,C988172,4,4,4,4,5,3000.85
4,I337046,C189076,5,5,5,5,4,60.60

In [44]:
invoice_sales.to_sql(TABLE_INVOICES_SALES, engine, if_exists='append', index=False)

457