In [1]:
!pip install sqlalchemy
!pip install psycopg2
!pip install pandas
!pip install numpy

Requirement already satisfied: sqlalchemy in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\junar\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

Collecting psycopg2
  Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2-2.9.11-cp314-cp314-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 721.8 kB/s eta 0:00:04
   ------- -------------------------------- 0.5/2.8 MB 721.8 kB/s eta 0:00:04
   --------------------------------- ------ 2.4/2.8 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 2.9 MB/s  0:00:01
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.11

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\junar\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\junar\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\junar\appdata\local\programs\python\python314\lib\site-packages (2.4.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\junar\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

# Imports Necesarios

In [2]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text

# Engine para conexión con la BD

In [3]:
engine = create_engine("postgresql://neondb_owner:npg_y2lGCWhAc9rj@ep-red-pine-aiww3s9a-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require")
print('Conexión establecida correctamente')

Conexión establecida correctamente

# Carga del Dataset

In [4]:
df = pd.read_csv('customer_shopping_data.csv')
print(f'Dataset cargado: {df.shape[0]:,} filas x {df.shape[1]} columnas')
df.head()

Dataset cargado: 99,457 filas x 10 columnas

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

# Tablas para BD

In [5]:
TABLE_INVOICES_SALES = 'invoice_sales'
TABLE_DIM_CUSTOMERS  = 'dim_customers'
TABLE_DIM_PRODUCTS   = 'dim_products'
TABLE_DIM_TIME       = 'dim_time'
TABLE_PAYMENTS       = 'dim_payment_methods'
TABLE_SHOPPING_MALL  = 'dim_shopping_malls'

# Limpiar tablas antes de cargar
Se eliminan los datos previos para evitar duplicados al re-ejecutar el notebook.

In [6]:
tablas_a_limpiar = [
    TABLE_INVOICES_SALES,
    TABLE_DIM_PRODUCTS,
    TABLE_SHOPPING_MALL,
    TABLE_PAYMENTS,
    TABLE_DIM_TIME,
    TABLE_DIM_CUSTOMERS
]

with engine.begin() as conn:
    for tabla in tablas_a_limpiar:
        try:
            conn.execute(text(f'TRUNCATE TABLE {tabla} CASCADE'))
            print(f'  {tabla}: limpiada')
        except Exception as e:
            print(f'  {tabla}: no existe aún ({e})')

print('\nTablas listas para carga inicial.')

  invoice_sales: limpiada
  dim_products: limpiada
  dim_shopping_malls: limpiada
  dim_payment_methods: limpiada
  dim_time: limpiada
  dim_customers: limpiada

Tablas listas para carga inicial.

# Dim Products
Solo se cargan las **8 categorías únicas** del dataset.

In [7]:
dim_products = df[['category']].drop_duplicates().reset_index(drop=True)
dim_products['id_dim_product'] = dim_products.index + 1
dim_products = dim_products[['id_dim_product', 'category']]

print(f'dim_products: {len(dim_products)} registros únicos')
dim_products

dim_products: 8 registros únicos

   id_dim_product         category
0               1         Clothing
1               2            Shoes
2               3            Books
3               4        Cosmetics
4               5  Food & Beverage
5               6             Toys
6               7       Technology
7               8         Souvenir

In [8]:
try:
    dim_products.to_sql(TABLE_DIM_PRODUCTS, engine, if_exists='append', index=False)
    print(f'dim_products cargada: {len(dim_products)} registros')
except Exception as e:
    print(f'Error cargando dim_products: {e}')
    raise

dim_products cargada: 8 registros

# Dim Customers
Se carga un registro por cada **customer_id único**.

In [9]:
dim_customers = df[['customer_id', 'gender', 'age']].drop_duplicates(subset=['customer_id']).reset_index(drop=True)
dim_customers = dim_customers.rename(columns={'customer_id': 'id_customer'})

print(f'dim_customers: {len(dim_customers)} registros únicos')
dim_customers.head()

dim_customers: 99457 registros únicos

  id_customer  gender  age
0     C241288  Female   28
1     C111565    Male   21
2     C266599    Male   20
3     C988172  Female   66
4     C189076  Female   53

In [10]:
try:
    dim_customers.to_sql(TABLE_DIM_CUSTOMERS, engine, if_exists='append', index=False)
    print(f'dim_customers cargada: {len(dim_customers)} registros')
except Exception as e:
    print(f'Error cargando dim_customers: {e}')
    raise

dim_customers cargada: 99457 registros

# Dim Time
Solo se cargan las **797 fechas únicas** del dataset.

In [11]:
dim_time = df[['invoice_date']].drop_duplicates().reset_index(drop=True)
dim_time['invoice_date'] = pd.to_datetime(dim_time['invoice_date'], dayfirst=True)
dim_time = dim_time.sort_values('invoice_date').reset_index(drop=True)
dim_time['id_dim_time'] = dim_time.index + 1
dim_time['day']   = dim_time['invoice_date'].dt.day
dim_time['month'] = dim_time['invoice_date'].dt.month
dim_time['year']  = dim_time['invoice_date'].dt.year
dim_time = dim_time[['id_dim_time', 'invoice_date', 'day', 'month', 'year']]

print(f'dim_time: {len(dim_time)} registros únicos')
dim_time.head()

dim_time: 797 registros únicos

   id_dim_time invoice_date  day  month  year
0            1   2021-01-01    1      1  2021
1            2   2021-01-02    2      1  2021
2            3   2021-01-03    3      1  2021
3            4   2021-01-04    4      1  2021
4            5   2021-01-05    5      1  2021

In [12]:
try:
    dim_time.to_sql(TABLE_DIM_TIME, engine, if_exists='append', index=False)
    print(f'dim_time cargada: {len(dim_time)} registros')
except Exception as e:
    print(f'Error cargando dim_time: {e}')
    raise

dim_time cargada: 797 registros

# Dim Shopping Malls
Solo se cargan los **10 centros comerciales únicos**.

In [13]:
dim_shopping_malls = df[['shopping_mall']].drop_duplicates().reset_index(drop=True)
dim_shopping_malls = dim_shopping_malls.rename(columns={'shopping_mall': 'shopping_mall_name'})
dim_shopping_malls['id_dim_shopping_mall'] = dim_shopping_malls.index + 1
dim_shopping_malls = dim_shopping_malls[['id_dim_shopping_mall', 'shopping_mall_name']]

print(f'dim_shopping_malls: {len(dim_shopping_malls)} registros únicos')
dim_shopping_malls

dim_shopping_malls: 10 registros únicos

   id_dim_shopping_mall shopping_mall_name
0                     1             Kanyon
1                     2     Forum Istanbul
2                     3          Metrocity
3                     4       Metropol AVM
4                     5       Istinye Park
5                     6   Mall of Istanbul
6                     7  Emaar Square Mall
7                     8        Cevahir AVM
8                     9     Viaport Outlet
9                    10       Zorlu Center

In [14]:
try:
    dim_shopping_malls.to_sql(TABLE_SHOPPING_MALL, engine, if_exists='append', index=False)
    print(f'dim_shopping_malls cargada: {len(dim_shopping_malls)} registros')
except Exception as e:
    print(f'Error cargando dim_shopping_malls: {e}')
    raise

dim_shopping_malls cargada: 10 registros

# Dim Payment Methods
Solo se cargan los **3 métodos de pago únicos**.

In [15]:
dim_payment_methods = df[['payment_method']].drop_duplicates().reset_index(drop=True)
dim_payment_methods = dim_payment_methods.rename(columns={'payment_method': 'payment_method_name'})
dim_payment_methods['id_dim_payment_method'] = dim_payment_methods.index + 1
dim_payment_methods = dim_payment_methods[['id_dim_payment_method', 'payment_method_name']]

print(f'dim_payment_methods: {len(dim_payment_methods)} registros únicos')
dim_payment_methods

dim_payment_methods: 3 registros únicos

   id_dim_payment_method payment_method_name
0                      1         Credit Card
1                      2          Debit Card
2                      3                Cash

In [16]:
try:
    dim_payment_methods.to_sql(TABLE_PAYMENTS, engine, if_exists='append', index=False)
    print(f'dim_payment_methods cargada: {len(dim_payment_methods)} registros')
except Exception as e:
    print(f'Error cargando dim_payment_methods: {e}')
    raise

dim_payment_methods cargada: 3 registros

# Invoice Sales
Se construye la tabla de hechos mapeando las **FK reales** desde cada dimensión.

In [17]:
invoice_sales = df[['invoice_no', 'customer_id', 'category', 'payment_method',
                     'shopping_mall', 'invoice_date', 'quantity', 'price']].copy()

invoice_sales = invoice_sales.rename(columns={'invoice_no': 'id_invoice'})

# Convertir fecha para poder hacer el merge con dim_time
invoice_sales['invoice_date'] = pd.to_datetime(invoice_sales['invoice_date'], dayfirst=True)

# Mapear FK de cada dimensión mediante merge
invoice_sales = invoice_sales.merge(
    dim_products[['id_dim_product', 'category']],
    on='category', how='left'
)
invoice_sales = invoice_sales.merge(
    dim_payment_methods[['id_dim_payment_method', 'payment_method_name']],
    left_on='payment_method', right_on='payment_method_name', how='left'
)
invoice_sales = invoice_sales.merge(
    dim_shopping_malls[['id_dim_shopping_mall', 'shopping_mall_name']],
    left_on='shopping_mall', right_on='shopping_mall_name', how='left'
)
invoice_sales = invoice_sales.merge(
    dim_time[['id_dim_time', 'invoice_date']],
    on='invoice_date', how='left'
)

# Usar customer_id directamente como FK (ya es el ID del cliente)
invoice_sales = invoice_sales.rename(columns={'customer_id': 'id_customer'})

invoice_sales = invoice_sales[['id_invoice', 'id_customer', 'id_dim_product',
                                'id_dim_payment_method', 'id_dim_shopping_mall',
                                'id_dim_time', 'quantity', 'price']]

print(f'invoice_sales preparada: {len(invoice_sales):,} registros')
invoice_sales.head()

invoice_sales preparada: 99,457 registros

,id_invoice,id_customer,id_dim_product,id_dim_payment_method,id_dim_shopping_mall,id_dim_time,quantity,price
0,I138884,C241288,1,1,1,582,5,1500.40
1,I317333,C111565,2,2,2,346,3,1800.51
2,I127801,C266599,1,3,3,313,1,300.08
3,I173702,C988172,2,1,4,136,5,3000.85
4,I337046,C189076,3,3,1,297,4,60.60

In [18]:
try:
    invoice_sales.to_sql(TABLE_INVOICES_SALES, engine, if_exists='append',
                         index=False, method='multi', chunksize=1000)
    print(f'invoice_sales cargada: {len(invoice_sales):,} registros')
except Exception as e:
    print(f'Error cargando invoice_sales: {e}')
    raise

invoice_sales cargada: 99,457 registros

# Verificación Post-Carga
Se comprueba que los registros cargados son correctos y no hay duplicados.

In [19]:
query = """
SELECT 'dim_customers'       AS tabla, COUNT(*) AS total, COUNT(DISTINCT id_customer)         AS unicos FROM dim_customers
UNION ALL
SELECT 'dim_products',                 COUNT(*),          COUNT(DISTINCT category)             FROM dim_products
UNION ALL
SELECT 'dim_shopping_malls',           COUNT(*),          COUNT(DISTINCT shopping_mall_name)   FROM dim_shopping_malls
UNION ALL
SELECT 'dim_payment_methods',          COUNT(*),          COUNT(DISTINCT payment_method_name)  FROM dim_payment_methods
UNION ALL
SELECT 'dim_time',                     COUNT(*),          COUNT(DISTINCT invoice_date)         FROM dim_time
UNION ALL
SELECT 'invoice_sales',                COUNT(*),          COUNT(DISTINCT id_invoice)           FROM invoice_sales
ORDER BY tabla
"""

df_verificacion = pd.read_sql_query(query, engine)
print('=== VERIFICACIÓN POST-CARGA ===')
print(df_verificacion.to_string(index=False))
print(f'\nTotal registros cargados: {df_verificacion["total"].sum():,}')

=== VERIFICACIÓN POST-CARGA ===
              tabla  total  unicos
      dim_customers  99457   99457
dim_payment_methods      3       3
       dim_products      8       8
 dim_shopping_malls     10      10
           dim_time    797     797
      invoice_sales  99457   99457

Total registros cargados: 199,732

In [20]:
engine.dispose()
print('Conexión cerrada. Carga inicial completada exitosamente.')

Conexión cerrada. Carga inicial completada exitosamente.